//  Copyright (c) 2015 Diyor Islomov. All rights reserved.
//	diyor.islomov@gmail.com || @iDiyor 
#ifndef __EC_GAME_HELPER_H__
#define __EC_GAME_HELPER_H__

// ACHIEVEMENTS
#define ACHIEVEMENT_CHAPTER_ONE_COMPLETED "CgkI1eGpqYoYEAIQAQ"
#define ACHIEVEMENT_CHAPTER_TWO_COMPLETED "CgkI1eGpqYoYEAIQAg"
#define ACHIEVEMENT_CHAPTER_THREE_COMPLETED "CgkI1eGpqYoYEAIQAw"
#define ACHIEVEMENT_CHAPTER_FOUR_COMPLETED "CgkI1eGpqYoYEAIQBA"
#define ACHIEVEMENT_MASTER_OF_ELECTROCITY "CgkI1eGpqYoYEAIQBQ"

// LEADERBOARD
#define LEADERBOARD_HIGH_SCORE "CgkI1eGpqYoYEAIQAA"

typedef enum {
	TYPE_BUILDING,
	TYPE_TOWER
} NodeType;


#endif // __EC_GAME_HELPER_H__